include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unnecessary_string_interpolations: true
    prefer_is_empty: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_local_variables: true
    unnecessary_this: true
    unnecessary_new: true
    unnecessary_const: true
    avoid_empty_else: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
