include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Clean Architecture enforcement
    avoid_print: false  # We use print for demo/debug
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Code style
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_single_quotes: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
